package com.psk1.mybatis.dao;

import com.psk1.mybatis.model.Artwork;
import com.psk1.mybatis.model.Author;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ArtworkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARTWORK
     *
     * @mbg.generated Fri Apr 01 14:50:09 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARTWORK
     *
     * @mbg.generated Fri Apr 01 14:50:09 EEST 2022
     */
    int insert(Artwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARTWORK
     *
     * @mbg.generated Fri Apr 01 14:50:09 EEST 2022
     */
    Artwork selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARTWORK
     *
     * @mbg.generated Fri Apr 01 14:50:09 EEST 2022
     */
    List<Artwork> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARTWORK
     *
     * @mbg.generated Fri Apr 01 14:50:09 EEST 2022
     */
    int updateByPrimaryKey(Artwork record);
}