package com.psk1.mybatis.dao;

import com.psk1.mybatis.model.Author;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface AuthorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTHOR
     *
     * @mbg.generated Fri Apr 01 14:50:09 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTHOR
     *
     * @mbg.generated Fri Apr 01 14:50:09 EEST 2022
     */
    int insert(Author record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTHOR
     *
     * @mbg.generated Fri Apr 01 14:50:09 EEST 2022
     */
    Author selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTHOR
     *
     * @mbg.generated Fri Apr 01 14:50:09 EEST 2022
     */
    List<Author> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTHOR
     *
     * @mbg.generated Fri Apr 01 14:50:09 EEST 2022
     */
    int updateByPrimaryKey(Author record);
}