package com.psk1.mybatis.model;

public class Exhibition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EXHIBITION.ID
     *
     * @mbg.generated Fri Apr 01 14:50:09 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EXHIBITION.NAME
     *
     * @mbg.generated Fri Apr 01 14:50:09 EEST 2022
     */
    private String name;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EXHIBITION.ID
     *
     * @return the value of PUBLIC.EXHIBITION.ID
     *
     * @mbg.generated Fri Apr 01 14:50:09 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EXHIBITION.ID
     *
     * @param id the value for PUBLIC.EXHIBITION.ID
     *
     * @mbg.generated Fri Apr 01 14:50:09 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EXHIBITION.NAME
     *
     * @return the value of PUBLIC.EXHIBITION.NAME
     *
     * @mbg.generated Fri Apr 01 14:50:09 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EXHIBITION.NAME
     *
     * @param name the value for PUBLIC.EXHIBITION.NAME
     *
     * @mbg.generated Fri Apr 01 14:50:09 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

}